version: "3.9"
services:
  frontend:
    image: sahanpunchihewa19/research-frontend:dev
    container_name: research-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.development
    restart: always
  
  backend:
    image: sahanpunchihewa19/research-backend:dev
    container_name: research-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  notification:
    image: sahanpunchihewa19/research-notification:dev
    container_name: research-notification
    ports:
      - "5006:5006"
    env_file:
      - ./notification/.env
    restart: always 
  
  inventory:
    image: sahanpunchihewa19/research-inventory-model:dev
    container_name: research-inventory-model
    ports:
      - "8000:8000"
    restart: always

  hair:
    image: sahanpunchihewa19/research-hair-donation:dev
    container_name: research-hair-donation
    ports:
      - "3000:3000"
    restart: always
  
  blood:
    image: sahanpunchihewa19/research-blood-donation:dev
    container_name: research-blood-donation
    ports:
      - "3001:3001"
    restart: always